// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ePermitsApp.Data;

#nullable disable

namespace ePermitsApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260211095032_AddUserandUserProfileSeed")]
    partial class AddUserandUserProfileSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ePermits.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("ePermits.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ePermits.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("LGUId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LGUId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 2, 11, 9, 50, 32, 293, DateTimeKind.Utc).AddTicks(4639),
                            CreatedBy = "System",
                            DepartmentId = 1,
                            LGUId = 1,
                            Password = "Password123!",
                            UserProfileId = 10,
                            UserRoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 2, 11, 9, 50, 32, 293, DateTimeKind.Utc).AddTicks(4645),
                            CreatedBy = "System",
                            DepartmentId = 1,
                            LGUId = 1,
                            Password = "Password123!",
                            UserProfileId = 11,
                            UserRoleId = 2,
                            Username = "govtuser"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 2, 11, 9, 50, 32, 293, DateTimeKind.Utc).AddTicks(4648),
                            CreatedBy = "System",
                            LGUId = 1,
                            Password = "Password123!",
                            UserProfileId = 12,
                            UserRoleId = 3,
                            Username = "applicant"
                        });
                });

            modelBuilder.Entity("ePermits.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 2, 11, 9, 50, 32, 293, DateTimeKind.Utc).AddTicks(4722),
                            CreatedBy = "System",
                            Email = "admin@epermits.gov",
                            FirstName = "Admin",
                            LastName = "User",
                            MiddleName = "System",
                            MobileNo = "09171234567",
                            UserId = 12
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 2, 11, 9, 50, 32, 293, DateTimeKind.Utc).AddTicks(4728),
                            CreatedBy = "System",
                            Email = "govtuser@epermits.gov",
                            FirstName = "Government",
                            LastName = "User",
                            MiddleName = "IT",
                            MobileNo = "09171234568",
                            UserId = 13
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 2, 11, 9, 50, 32, 293, DateTimeKind.Utc).AddTicks(4732),
                            CreatedBy = "System",
                            Email = "applicant@example.com",
                            FirstName = "Juan",
                            LastName = "Cruz",
                            MiddleName = "Dela",
                            MobileNo = "09171234569",
                            UserId = 14
                        });
                });

            modelBuilder.Entity("ePermits.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRoleDesc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 11, 9, 50, 32, 293, DateTimeKind.Utc).AddTicks(4416),
                            CreatedBy = "System",
                            UserRoleDesc = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 11, 9, 50, 32, 293, DateTimeKind.Utc).AddTicks(4421),
                            CreatedBy = "System",
                            UserRoleDesc = "user"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 11, 9, 50, 32, 293, DateTimeKind.Utc).AddTicks(4424),
                            CreatedBy = "System",
                            UserRoleDesc = "applicant"
                        });
                });

            modelBuilder.Entity("ePermitsApp.Entities.Barangay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BarangayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LGUId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BarangayName");

                    b.HasIndex("LGUId");

                    b.ToTable("Barangays");
                });

            modelBuilder.Entity("ePermitsApp.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LGUId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LGUId", "DepartmentCode")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 11, 9, 50, 32, 293, DateTimeKind.Utc).AddTicks(4863),
                            CreatedBy = "System",
                            DepartmentCode = "IT",
                            DepartmentName = "Information Technology",
                            IsDeleted = false,
                            LGUId = 1
                        });
                });

            modelBuilder.Entity("ePermitsApp.Entities.LGU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LGUName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId", "LGUName");

                    b.ToTable("LGUs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 11, 9, 50, 32, 293, DateTimeKind.Utc).AddTicks(4820),
                            CreatedBy = "System",
                            IsDeleted = false,
                            LGUName = "Consolacion",
                            ProvinceId = 1
                        });
                });

            modelBuilder.Entity("ePermitsApp.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceName");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 11, 9, 50, 32, 293, DateTimeKind.Utc).AddTicks(4780),
                            CreatedBy = "System",
                            IsDeleted = false,
                            ProvinceName = "Cebu"
                        });
                });

            modelBuilder.Entity("ePermits.Models.Application", b =>
                {
                    b.HasOne("ePermits.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ePermits.Models.Message", b =>
                {
                    b.HasOne("ePermits.Models.Application", "Application")
                        .WithMany("Messages")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ePermits.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("ePermits.Models.User", b =>
                {
                    b.HasOne("ePermitsApp.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ePermitsApp.Entities.LGU", "LGU")
                        .WithMany()
                        .HasForeignKey("LGUId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ePermits.Models.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("LGU");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("ePermits.Models.UserProfile", b =>
                {
                    b.HasOne("ePermits.Models.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("ePermits.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ePermitsApp.Entities.Barangay", b =>
                {
                    b.HasOne("ePermitsApp.Entities.LGU", "LGU")
                        .WithMany()
                        .HasForeignKey("LGUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LGU");
                });

            modelBuilder.Entity("ePermitsApp.Entities.Department", b =>
                {
                    b.HasOne("ePermitsApp.Entities.LGU", "LGU")
                        .WithMany()
                        .HasForeignKey("LGUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LGU");
                });

            modelBuilder.Entity("ePermitsApp.Entities.LGU", b =>
                {
                    b.HasOne("ePermitsApp.Entities.Province", "Province")
                        .WithMany("LGUs")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ePermits.Models.Application", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ePermits.Models.User", b =>
                {
                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ePermits.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ePermitsApp.Entities.Province", b =>
                {
                    b.Navigation("LGUs");
                });
#pragma warning restore 612, 618
        }
    }
}
